"""update erd v1

Revision ID: 8c7c39ca6077
Revises: dae35cc5b34a
Create Date: 2026-06-16 16:11:17.736170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c7c39ca6077'
down_revision: Union[str, Sequence[str], None] = 'dae35cc5b34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # batch_alter_table: SQLite 는 ALTER COLUMN 이 없어서 alembic 이
    # "새 테이블 -> 복사 -> 이름 교체" 로 우회한다. Postgres 에서는 그냥 ALTER 로 나간다.
    op.add_column('assets', sa.Column('storage_gb', sa.Integer(), nullable=True))
    with op.batch_alter_table('assets') as batch:
        batch.alter_column('asset_no',
                   existing_type=sa.VARCHAR(length=50),
                   nullable=True)
        batch.alter_column('asset_type',
                   existing_type=sa.VARCHAR(length=30),
                   nullable=True)
        batch.alter_column('created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   type_=sa.TIMESTAMP(),
                   existing_nullable=True,
                   existing_server_default=sa.func.now())
    op.add_column('employees', sa.Column('company', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('location', sa.String(length=100), nullable=True))
    with op.batch_alter_table('employees') as batch:
        batch.alter_column('created_at',
                   existing_type=postgresql.TIMESTAMP(timezone=True),
                   type_=sa.TIMESTAMP(),
                   existing_nullable=True,
                   existing_server_default=sa.func.now())
    op.add_column('license_pools', sa.Column('alert_days', sa.Integer(), nullable=True))
    op.add_column('software_products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('software_products', 'description')
    op.drop_column('license_pools', 'alert_days')
    op.alter_column('employees', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.func.now())
    op.drop_column('employees', 'location')
    op.drop_column('employees', 'company')
    op.alter_column('assets', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.func.now())
    op.alter_column('assets', 'asset_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('assets', 'asset_no',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('assets', 'storage_gb')
    # ### end Alembic commands ###
