"""create software tables

Revision ID: dae35cc5b34a
Revises: 047d56f14f9c
Create Date: 2026-06-16 15:40:53.693821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dae35cc5b34a'
down_revision: Union[str, Sequence[str], None] = '047d56f14f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('license_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_pools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('purchased_count', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('software_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('software_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('installed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['software_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software_installations')
    op.drop_table('license_pools')
    op.drop_table('software_products')
    # ### end Alembic commands ###
